### ISSUE TITLE
Parse Server

### ISSUE THREAD

**Issue by man2** [TBaudon/extension-parse#2]
Does this work with the open source parse server?

**Comment by man2** [comment]
bump @TBaudon

**Comment by Tomobodo** [comment]
Hi, I don't know, made it with parse SDK, but now parse is closing or already closed so it's out of date. I didn't know there was an open source server, never tried to connect it, so it certainly doesn't work with open source server.

**Comment by man2** [comment]
with just a little modification, it's working with the new parse server.. i'll make PR soon
